services:
  app_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    expose:
      - "5173"
    depends_on:
      - app_backend
    restart: always
   
  app_backend:
    build:  
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    expose:
      - "5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: food_delivery
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - app_db
    restart: always

  app_db:
    build:
     context: ./backend/src/db/schema
     dockerfile: Dockerfile
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_delivery
    volumes:
      - ./db/db_data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  nginx:
    image: nginx:latest
    container_name: qb_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_frontend
      - app_backend
    restart: always
volumes:
  postgres_data:
